name: WIP
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - closed

jobs:
  check-linked-issues:
    name: Fetch issues
    runs-on: ubuntu-latest
    outputs:
      linked_issues: ${{ steps.issue-output.outputs.linked_issues }}
    steps:
      - name: Get issues
        id: get-issues
        uses: mondeja/pr-linked-issues-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set output
        id: issue-output
        run: echo "linked_issues=${{ steps.get-issues.outputs.issues }}" >> $GITHUB_OUTPUT
  
  label-issues:
    name: Label issues
    runs-on: ubuntu-latest
    needs: check-linked-issues
    if: join(needs.check-linked-issues.outputs.linked_issues) != ''
    steps:
      - name: Print details
        id: print-details
        run: echo "${{ github.event.action }} ${{  needs.check-linked-issues.outputs.linked_issues  }}"
      - name: Label issue (PR Open)
        if: github.event.action != 'closed'
        uses: actions/github-script@v6
        with:
          script: |
            const issues = echo [\"${{  needs.check-linked-issues.outputs.linked_issues  }}\"] |sed 's/,/\", \"/g'
            for (const issue of issues) {
              if (${{ github.event.action }} != "closed")
                github.rest.issues.addLabels({
                  issue_number: issue,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  labels: ["work-in-progress"]
                })
              else
                github.rest.issues.removeLabel({
                  issue_number: issue,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  name: ["work-in-progress"]
                })
            }
