name: Work in Progress

on:
  pull_request:
    types: [opened, closed]

jobs:
  update-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/labeler@v2
        with:
          labels: work-in-progress
          add-label: true
          remove-label: true
